# Generated by Django 2.1.3 on 2018-12-22 03:52

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyView',
            fields=[
                ('todoitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todolist.TodoItem')),
            ],
            bases=(django.contrib.auth.mixins.LoginRequiredMixin, 'todolist.todoitem'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='personalpg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
