# Generated by Django 2.1.3 on 2018-12-24 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20181221_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoitem',
            name='personalpg',
        ),
    ]
